services:
  astrowind:
    build: .
    container_name: astrowind
    ports:
      - 8080:8080

  formatter:
    image: personal-blog-formatter
    profiles: [tools]
    build:
      context: .
      target: deps
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: [node, scripts/format.mjs]
    command: [--write, .]

  post-templates:
    extends:
      service: formatter
    entrypoint: [node, scripts/post-templates.mjs]
    command: [--watch]
